Update to FreeType 2.1.8
svn path=/trunk/; revision=9349

diff --git a/reactos/lib/freetype/configure b/reactos/lib/freetype/configure
--- a/reactos/lib/freetype/configure
+++ b/reactos/lib/freetype/configure
@@ -5,7 +5,6 @@
 # This should re-generate the following files:
 #
 #   config.mk
-#   Jamfile
 #   install
 #
 
@@ -14,9 +13,14 @@ if test "x$GNUMAKE" = x; then
 fi
 
 if test -z "`$GNUMAKE -v 2>/dev/null | grep GNU`"; then
-  echo "Sorry, GNU make is required to build FreeType2." >&2
-  echo "Please try \`GNUMAKE=<GNU make command name> $0'." >&2
-  exit 1
+  if test -z "`$GNUMAKE -v 2>/dev/null | grep makepp`"; then
+    echo "GNU make (>= 3.79.1) or makepp (>= 1.19) is required to build FreeType2." >&2
+    echo "Please try" >&2
+    echo "  \`GNUMAKE=<GNU make command name> $0'." >&2
+    echo "or >&2"
+    echo "  \`GNUMAKE=\"makepp --norc-substitution\" $0'." >&2
+    exit 1
+  fi
 fi
 
 # Uh, oh.  This is taken from autoconf.  They know what they are doing...
